# In: user-service/src/main/resources/application.yml

spring:
  profiles:
    active: dev
  application:
    # This is the most important line.
    # It's the service's name in Eureka and the name of its config file.
    name: user-service

  # This tells the app how to find the Config Server
  config:
    #import: "configserver:http://config-server:8888"
    import: "configserver:http://localhost:8888"